/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSU54TkI3YXdqY2ZxOSt6MjV6REZudTR2MVprV2RteXREbkFpLzRDT04yND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTTB0MnN0bzd3Wm5GSHdjRURXMHg4VE96ZGllb2szd3drUm1LRnJwNnNrYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHQWFyb0hBOW0vclZUZGxDUW1nbHhjNGtXemR0dDhEYmJsSkhiaWhPR244PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJaUDlwUExSY0h6QURDSXI5dUR4SXdRZTcwdmdTampybHl6WEFraUNGZlJzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJBdnZid0Q1dzhMZDZSdkoxRFBPL0ROMUdQdVRmSitQS3BxTUZDaFVqWG89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImpDU0JDeUJLRXBpTzNFYWtPaVFya090ZkZYZStoZTFub2dSMmNTc1FWemM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0VLWmk5UHJmUWRCbDEyeFZSVmFvYWNVdjN0czd1UlpqcmhWdkVRQlZGUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNzNqZmw2aTZCK05yZ3J0WnZaZXdiT3ZSMzlILzZQamxNWU9SZVRCQUtDST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklQT0JIT05lc1oyd2NoY045dStSSnpQTUNGVVMybDlJMXZWdXpXUVhTUWNHWm1rM1MyQzVzbEM4b0pGQWV4cmdsVWcyR1Q5aEk0dDhIRDRBTmFvTml3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTcyLCJhZHZTZWNyZXRLZXkiOiJ5cEZhS0M3Qk84S0I1VTg1blp4UHN6REZDYkNHVlZMY1pkZjVJSHBxSmZBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJJeF9fanUzV1J2dVJUR01ISjh6RE5RIiwicGhvbmVJZCI6IjAxMmRiZDc4LTk1ZjctNDI1OS1hMjk4LWEzZWUyNzYyMGFmOCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJKTmV6OGdKZTZCN0NESUI5bVJXZmUrNnNTcjQ9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTldaK0I4cnpqWjFXT0RTRGFwTXo0S1ZyNGRNPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkVEQzFLRkVKIiwibWUiOnsiaWQiOiIyMzM1OTIxMjM5MjI6NEBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJESiBPQk9ZRSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTmlHdmNRRkVMU0cycmtHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoibVFxVHpybUxhZ3FBYW1TTURIRndTNlhMWkQ0Mk9xTmJseHVOZk1qMVB4dz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiVWxvOXBXeGZ2SUJNTVNiY3ZFWFl1SEVzZzhnL0ZhbVM1S28rdkhBTU9hRmE0SU50UXg1TjYraTZmb0l4UkcwNk9aT2FDckUyR0g3TUM3c3BSZm9QRFE9PSIsImRldmljZVNpZ25hdHVyZSI6ImcySFROSUd6NXNTclZYL2JOQU1rT01nS29rNzcrbHIyRFR6a21BenU0MTBaQjU4c1NXRm90VnVnWDBCM0kveHI4K2dlcEZJYVRWcUtJUHRnVUtpZGh3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjMzNTkyMTIzOTIyOjRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWmtLazg2NWkyb0tnR3BrakF4eGNFdWx5MlErTmpxalc1Y2JqWHpJOVQ4YyJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMTYyNTc5NCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBUnUifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
