/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUl1dU93MjJhRjYzd3M2VVNxUHJnaG9HNm5BM3FaS3p0ek5ZVVMvWkRHUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVHdLNnJNQXF3TXBYM0tiMHBCdUpUbjkvWHgrZ2ltbFc1T3d1Y1VxbHVBcz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0QldSWUxwZTBVcUM3MW9HR2ZYR2Yvc1A3RDE0elhkUUxNbGh4Zk5yL21vPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJQVU5CMFZtTGx6S0NkWHRldktpa3FrYVFmQVE3M25ZTEtuVnFyZzN0UUY4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkVCTG9ONC83Vys0TDdoOFc5VmlyemQ0d2Z2RWZmVTRmdGdxYWpWWDlkVXM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJSREpWYzhlK1JIWERhcmlmeFZPZkVaalZ6ZXQzYlFVSERIN2l3d3BSd2M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ0ZqYk5GL09rSFRvaW5MdjMyWEJhZHZjRzhPSFE1NXFyd1M4NWQ2b2QyWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS1RUOWhZSFdhRVNlYzBDY3p3OVVDUGUxb2l2eUREQWxqNjBUeU1oOVJIMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjlQMWcvU1M2aWFSY21TMFlDMnp3YlRla1h6SGRkU1YrRUc2K2d2ZkMvYVlYZjNJbldiaGs1TmxRSUM1ZWN4M0hZZjVFQzIvcjFTUnBKeWpVQmo2dGd3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODYsImFkdlNlY3JldEtleSI6Ik43bm1hWnV0TjZ3WkxCZHd6WWl4bExNTENSS2tzR2NqY1hEQzRVSTY2NXc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Im82b1RuWi1zU3pPWXRiQXNLenhobHciLCJwaG9uZUlkIjoiOWMwNmM0ZjAtNGQzMy00MjYxLTgxMTgtNjc0Yjk1OGMyODE0IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhTcVptMEJCZDl3MSt4N2hnT2dxbTFUb0I0RT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5NkdsbGM5U01TSkZvSjdkVFN2OFRocGtnMTQ9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiUU5GVDZDNFAiLCJtZSI6eyJpZCI6IjIzMzU5MjEyMzkyMjo2QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkRKIE9CT1lFIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNOcUd2Y1FGRUlieTk3a0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJtUXFUenJtTGFncUFhbVNNREhGd1M2WExaRDQyT3FOYmx4dU5mTWoxUHh3PSIsImFjY291bnRTaWduYXR1cmUiOiJiTVlubm5yZXVhYWIrSUhBY0ZwNEVZWWUrZ2JCSWVDYThrb3dHT0VxcTVCU3BrREprb0dVWlBRVFJuNTlIdklUaXZiMUIrcXY4eG1UektKVjBhVGdCdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiSkl4eVZvMVpaTmlwdHBjTWFyYjc1ejFoY3Z1cU9TenU5NGxNWkFYeGY2UmFmc1laaG5UMFhJc0lXR0QvNElJNFdTM0RBNzBCd3ZZR3YwNzljOGNxaVE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzM1OTIxMjM5MjI6NkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJaa0trODY1aTJvS2dHcGtqQXh4Y0V1bHkyUStOanFqVzVjYmpYekk5VDhjIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMyMTE0NzA4LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU44RiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
